
-- ASTRA:INK 雲端存檔資料表
create table if not exists public.game_saves (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  save_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.game_saves enable row level security;

drop policy if exists "Users can read own save" on public.game_saves;
create policy "Users can read own save"
on public.game_saves for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own save" on public.game_saves;
create policy "Users can insert own save"
on public.game_saves for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own save" on public.game_saves;
create policy "Users can update own save"
on public.game_saves for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 可選：每次更新自動刷新 updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_game_saves_updated on public.game_saves;
create trigger trg_game_saves_updated
before update on public.game_saves
for each row execute procedure public.set_updated_at();


-- V7: 雲端存檔版本欄位
alter table public.game_saves
add column if not exists save_version integer not null default 1;

-- 安全經濟系統範本：
-- 正式營運時，星鑽與抽卡不要讓瀏覽器直接 update。
-- 使用 ledger 保留每一筆星鑽增減紀錄，並由 Edge Function / server 驗證後寫入。
create table if not exists public.gem_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null,
  reason text not null,
  created_at timestamptz not null default now()
);

alter table public.gem_ledger enable row level security;

drop policy if exists "Users can read own gem ledger" on public.gem_ledger;
create policy "Users can read own gem ledger"
on public.gem_ledger for select
using (auth.uid() = user_id);

-- 注意：刻意不建立 client insert/update policy。
-- 玩家前端只能讀自己的 ledger；正式發放/扣除星鑽應由 server / Edge Function 使用 service role 寫入。
